### ISSUE TITLE
is this package in use?

### ISSUE THREAD

**Issue by elie222** [mixmaxhq/meteor-smart-disconnect#1]
very few lines of code, but i think im going to update it and use it

**Comment by bradvogel** [comment]
We don't use it anymore for other reasons, but it worked great while we did! Go ahead and try it.

**Comment by elie222** [comment]
thanks. made a pull request to make it more customisable

**Comment by elie222** [comment]
just out of interest, why did you stop using this package?

**Comment by bradvogel** [comment]
We were worried about to cost of reconnecting >30k connected clients all at once. But I'm sure this is fine for smaller meteor deployments.

**Comment by elie222** [comment]
I'm worried about large scale. That's even part of the reason I'm adding
this package.

How would you get into a situation where you'd reconnect to 30k users at
once? On an app update?
